get http://localhost:3000/products

### single product
get http://localhost:3000/products/65351b2f3a766e9ccd56a92f


### añadir product
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "product 3",
  "image": "https://www.crucial.mx/content/dam/crucial/articles/for-gamers/how-to-build-an-epic-gaming-pc/computer-motherboard.jpg.transform/large-jpg/img.jpg",
  "description": "some product hardware 2",
  "price": 1000,
  "category": "motherboard"
}


### detele a product
DELETE http://localhost:3000/products/653afd60ca788067c93f28c2

###
PUT http://localhost:3000/products/653aa5b3c132dce648f93f5c
Content-Type: application/json

{
  "title": "producto 3 verdadero"
}
